name: Newman report with Postman collection
on:
  push:
    branches:
      - main

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: Make Directory for results
        run: mkdir -p testResults

      - name: Run API tests
        continue-on-error: true
        run: |
          npx newman run petstore.collection.json -r cli,htmlextra --reporter-htmlextra-export ./testResults/index.html 
      - name: Output the run Details
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: testResults
          path: ./testResults 
      - name: Publish Github Pages
        if: ${{ always() }}
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./testResults
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com' 
